server:
  type: simple
  applicationContextPath: /konnichiwa
  adminContextPath: /admin
  connector:
    type: http
    port: 8080


logging:
    level: DEBUG


postAuthRedirect: 'yourPostAuth'
failureRedirect: 'yourRedirect'

slackClientId: 'yourClientId'
slackRedirect: 'http://localhost:8080/konnichiwa/auth/response'
slackSecret: YourSecret
slackSecret: YourSecret
slackTokenLocation: 'https://slack.com/api/oauth.access'
slackAuthorization: 'https://slack.com/oauth/authorize'